
-- Crear la base de datos
CREATE DATABASE estaciones_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;


-- DROP SCHEMA actividad1;

CREATE SCHEMA actividad1 AUTHORIZATION pg_database_owner;

-- actividad1.empresas definition

-- Drop table

-- DROP TABLE actividad1.empresas;

CREATE TABLE actividad1.empresas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	rotulo varchar(255) NULL,
	CONSTRAINT empresas_pkey PRIMARY KEY (id)
);


-- actividad1.provincias definition

-- Drop table

-- DROP TABLE actividad1.provincias;

CREATE TABLE actividad1.provincias (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NULL,
	CONSTRAINT provincias_pkey PRIMARY KEY (id)
);


-- actividad1.tipos_combustible definition

-- Drop table

-- DROP TABLE actividad1.tipos_combustible;

CREATE TABLE actividad1.tipos_combustible (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	categoria varchar(50) NULL,
	codigo varchar(50) NULL,
	descripcion varchar(500) NULL,
	nombre varchar(100) NULL,
	CONSTRAINT tipos_combustible_pkey PRIMARY KEY (id)
);


-- actividad1.municipios definition

-- Drop table

-- DROP TABLE actividad1.municipios;

CREATE TABLE actividad1.municipios (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NULL,
	provincia_id int8 NULL,
	CONSTRAINT municipios_pkey PRIMARY KEY (id),
	CONSTRAINT fkbknnfyvnp4vs6c8s4n3fken0v FOREIGN KEY (provincia_id) REFERENCES actividad1.provincias(id)
);


-- actividad1.embarcaciones definition

-- Drop table

-- DROP TABLE actividad1.embarcaciones;

CREATE TABLE actividad1.embarcaciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo_postal varchar(255) NULL,
	direccion varchar(255) NULL,
	horario varchar(500) NULL,
	latitud varchar(255) NULL,
	localidad varchar(255) NULL,
	longitud varchar(255) NULL,
	rem varchar(255) NULL,
	tipo_venta varchar(255) NULL,
	empresa_id int8 NULL,
	municipio_id int8 NULL,
	CONSTRAINT embarcaciones_pkey PRIMARY KEY (id),
	CONSTRAINT fk5q9mi3ee8nmudehri9fomjtv FOREIGN KEY (empresa_id) REFERENCES actividad1.empresas(id),
	CONSTRAINT fkkvnuyglf7pvy4nhjmnukm8poy FOREIGN KEY (municipio_id) REFERENCES actividad1.municipios(id)
);


-- actividad1.estaciones_servicio definition

-- Drop table

-- DROP TABLE actividad1.estaciones_servicio;

CREATE TABLE actividad1.estaciones_servicio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo_postal varchar(255) NULL,
	direccion varchar(255) NULL,
	horario varchar(500) NULL,
	latitud varchar(255) NULL,
	localidad varchar(255) NULL,
	longitud varchar(255) NULL,
	margen varchar(255) NULL,
	rem varchar(255) NULL,
	tipo_servicio varchar(255) NULL,
	tipo_venta varchar(255) NULL,
	toma_datos timestamp(6) NULL,
	empresa_id int8 NULL,
	municipio_id int8 NULL,
	CONSTRAINT estaciones_servicio_pkey PRIMARY KEY (id),
	CONSTRAINT fk3iu20tyny5329uayl1dd2mger FOREIGN KEY (municipio_id) REFERENCES actividad1.municipios(id),
	CONSTRAINT fks3hddb02xtktrn77vtvec2oi9 FOREIGN KEY (empresa_id) REFERENCES actividad1.empresas(id)
);


-- actividad1.precios_combustible definition

-- Drop table

-- DROP TABLE actividad1.precios_combustible;

CREATE TABLE actividad1.precios_combustible (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_precio timestamp(6) NULL,
	porcentaje numeric(5, 2) NULL,
	precio numeric(10, 3) NULL,
	estacion_id int8 NULL,
	tipo_combustible_id int8 NULL,
	CONSTRAINT precios_combustible_pkey PRIMARY KEY (id),
	CONSTRAINT fkdb9jcgkp2m5tfowmq8qtkhfn3 FOREIGN KEY (tipo_combustible_id) REFERENCES actividad1.tipos_combustible(id),
	CONSTRAINT fkswa060k0cecol4pmytf4k7tvk FOREIGN KEY (estacion_id) REFERENCES actividad1.estaciones_servicio(id)
);
CREATE INDEX idx_estacion_combustible ON actividad1.precios_combustible USING btree (estacion_id, tipo_combustible_id);
CREATE INDEX idx_fecha_precio ON actividad1.precios_combustible USING btree (fecha_precio);


-- actividad1.precios_embarcacion definition

-- Drop table

-- DROP TABLE actividad1.precios_embarcacion;

CREATE TABLE actividad1.precios_embarcacion (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_precio timestamp(6) NULL,
	precio numeric(10, 3) NULL,
	embarcacion_id int8 NULL,
	tipo_combustible_id int8 NULL,
	CONSTRAINT precios_embarcacion_pkey PRIMARY KEY (id),
	CONSTRAINT fk9u0lwrtcg701cn93nhb4x123w FOREIGN KEY (tipo_combustible_id) REFERENCES actividad1.tipos_combustible(id),
	CONSTRAINT fkbmom3ut29rfe45md5she00kem FOREIGN KEY (embarcacion_id) REFERENCES actividad1.embarcaciones(id)
);
CREATE INDEX idx_embarcacion_combustible ON actividad1.precios_embarcacion USING btree (embarcacion_id, tipo_combustible_id);
CREATE INDEX idx_fecha_precio_emb ON actividad1.precios_embarcacion USING btree (fecha_precio);